# Generated by Django 5.0.7 on 2024-07-18 19:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('servingsLeft', models.IntegerField()),
                ('totalServings', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('frequency', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='choreapi.feed')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choreHousehold', to='choreapi.household')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userHousehold', to='choreapi.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='householdUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
